// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/infoxtr.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RcppDisc
Rcpp::IntegerVector RcppDisc(const Rcpp::NumericVector& vec, int n, const std::string& method, int sample_begin, double sample_prob, int seed, double threshold, int iter_step, Rcpp::Nullable<Rcpp::NumericVector> breakpoints, bool right_closed);
RcppExport SEXP _infoxtr_RcppDisc(SEXP vecSEXP, SEXP nSEXP, SEXP methodSEXP, SEXP sample_beginSEXP, SEXP sample_probSEXP, SEXP seedSEXP, SEXP thresholdSEXP, SEXP iter_stepSEXP, SEXP breakpointsSEXP, SEXP right_closedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type sample_begin(sample_beginSEXP);
    Rcpp::traits::input_parameter< double >::type sample_prob(sample_probSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type iter_step(iter_stepSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type breakpoints(breakpointsSEXP);
    Rcpp::traits::input_parameter< bool >::type right_closed(right_closedSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDisc(vec, n, method, sample_begin, sample_prob, seed, threshold, iter_step, breakpoints, right_closed));
    return rcpp_result_gen;
END_RCPP
}
// RcppDist4Vec
double RcppDist4Vec(const Rcpp::NumericVector& v1, const Rcpp::NumericVector& v2, std::string method, bool na_rm);
RcppExport SEXP _infoxtr_RcppDist4Vec(SEXP v1SEXP, SEXP v2SEXP, SEXP methodSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDist4Vec(v1, v2, method, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppDist4Mat
Rcpp::NumericVector RcppDist4Mat(const Rcpp::NumericMatrix& mat, std::string method, bool na_rm, bool byrow);
RcppExport SEXP _infoxtr_RcppDist4Mat(SEXP matSEXP, SEXP methodSEXP, SEXP na_rmSEXP, SEXP byrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type byrow(byrowSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDist4Mat(mat, method, na_rm, byrow));
    return rcpp_result_gen;
END_RCPP
}
// RcppDist4MatSub
Rcpp::NumericVector RcppDist4MatSub(const Rcpp::NumericMatrix& mat, const Rcpp::IntegerVector& lib, const Rcpp::IntegerVector& pred, std::string method, bool na_rm, bool byrow);
RcppExport SEXP _infoxtr_RcppDist4MatSub(SEXP matSEXP, SEXP libSEXP, SEXP predSEXP, SEXP methodSEXP, SEXP na_rmSEXP, SEXP byrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type lib(libSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type byrow(byrowSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDist4MatSub(mat, lib, pred, method, na_rm, byrow));
    return rcpp_result_gen;
END_RCPP
}
// RcppDiscEntropy
double RcppDiscEntropy(SEXP series, double base, bool na_rm);
RcppExport SEXP _infoxtr_RcppDiscEntropy(SEXP seriesSEXP, SEXP baseSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type series(seriesSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDiscEntropy(series, base, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppContEntropy
double RcppContEntropy(const Rcpp::NumericVector& vec, int k, int alg, double base);
RcppExport SEXP _infoxtr_RcppContEntropy(SEXP vecSEXP, SEXP kSEXP, SEXP algSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type alg(algSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppContEntropy(vec, k, alg, base));
    return rcpp_result_gen;
END_RCPP
}
// RcppDiscJE
double RcppDiscJE(SEXP mat, const Rcpp::IntegerVector& vars, double base, bool na_rm);
RcppExport SEXP _infoxtr_RcppDiscJE(SEXP matSEXP, SEXP varsSEXP, SEXP baseSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDiscJE(mat, vars, base, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppContJE
double RcppContJE(const Rcpp::NumericMatrix& mat, const Rcpp::IntegerVector& vars, int k, int alg, double base);
RcppExport SEXP _infoxtr_RcppContJE(SEXP matSEXP, SEXP varsSEXP, SEXP kSEXP, SEXP algSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type alg(algSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppContJE(mat, vars, k, alg, base));
    return rcpp_result_gen;
END_RCPP
}
// RcppDiscCE
double RcppDiscCE(SEXP mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& conds, double base, bool na_rm);
RcppExport SEXP _infoxtr_RcppDiscCE(SEXP matSEXP, SEXP targetSEXP, SEXP condsSEXP, SEXP baseSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type conds(condsSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDiscCE(mat, target, conds, base, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// RcppContCE
double RcppContCE(const Rcpp::NumericMatrix& mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& conds, int k, int alg, double base);
RcppExport SEXP _infoxtr_RcppContCE(SEXP matSEXP, SEXP targetSEXP, SEXP condsSEXP, SEXP kSEXP, SEXP algSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type conds(condsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type alg(algSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppContCE(mat, target, conds, k, alg, base));
    return rcpp_result_gen;
END_RCPP
}
// RcppDiscMI
double RcppDiscMI(SEXP mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& interact, double base, bool na_rm, bool normalize);
RcppExport SEXP _infoxtr_RcppDiscMI(SEXP matSEXP, SEXP targetSEXP, SEXP interactSEXP, SEXP baseSEXP, SEXP na_rmSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type interact(interactSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDiscMI(mat, target, interact, base, na_rm, normalize));
    return rcpp_result_gen;
END_RCPP
}
// RcppContMI
double RcppContMI(const Rcpp::NumericMatrix& mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& interact, int k, int alg, double base, bool normalize);
RcppExport SEXP _infoxtr_RcppContMI(SEXP matSEXP, SEXP targetSEXP, SEXP interactSEXP, SEXP kSEXP, SEXP algSEXP, SEXP baseSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type interact(interactSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type alg(algSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppContMI(mat, target, interact, k, alg, base, normalize));
    return rcpp_result_gen;
END_RCPP
}
// RcppDiscCMI
double RcppDiscCMI(SEXP mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& interact, const Rcpp::IntegerVector& conds, double base, bool na_rm, bool normalize);
RcppExport SEXP _infoxtr_RcppDiscCMI(SEXP matSEXP, SEXP targetSEXP, SEXP interactSEXP, SEXP condsSEXP, SEXP baseSEXP, SEXP na_rmSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type interact(interactSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type conds(condsSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDiscCMI(mat, target, interact, conds, base, na_rm, normalize));
    return rcpp_result_gen;
END_RCPP
}
// RcppContCMI
double RcppContCMI(const Rcpp::NumericMatrix& mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& interact, const Rcpp::IntegerVector& conds, int k, int alg, double base, bool normalize);
RcppExport SEXP _infoxtr_RcppContCMI(SEXP matSEXP, SEXP targetSEXP, SEXP interactSEXP, SEXP condsSEXP, SEXP kSEXP, SEXP algSEXP, SEXP baseSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type interact(interactSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type conds(condsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type alg(algSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppContCMI(mat, target, interact, conds, k, alg, base, normalize));
    return rcpp_result_gen;
END_RCPP
}
// RcppDiscTE
double RcppDiscTE(SEXP mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& agent, int lag_p, int lag_q, double base, bool na_rm, bool normalize, bool lag_single);
RcppExport SEXP _infoxtr_RcppDiscTE(SEXP matSEXP, SEXP targetSEXP, SEXP agentSEXP, SEXP lag_pSEXP, SEXP lag_qSEXP, SEXP baseSEXP, SEXP na_rmSEXP, SEXP normalizeSEXP, SEXP lag_singleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type agent(agentSEXP);
    Rcpp::traits::input_parameter< int >::type lag_p(lag_pSEXP);
    Rcpp::traits::input_parameter< int >::type lag_q(lag_qSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< bool >::type lag_single(lag_singleSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppDiscTE(mat, target, agent, lag_p, lag_q, base, na_rm, normalize, lag_single));
    return rcpp_result_gen;
END_RCPP
}
// RcppContTE
double RcppContTE(const Rcpp::NumericMatrix& mat, const Rcpp::IntegerVector& target, const Rcpp::IntegerVector& agent, int lag_p, int lag_q, int k, int alg, double base, bool normalize, bool lag_single);
RcppExport SEXP _infoxtr_RcppContTE(SEXP matSEXP, SEXP targetSEXP, SEXP agentSEXP, SEXP lag_pSEXP, SEXP lag_qSEXP, SEXP kSEXP, SEXP algSEXP, SEXP baseSEXP, SEXP normalizeSEXP, SEXP lag_singleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type agent(agentSEXP);
    Rcpp::traits::input_parameter< int >::type lag_p(lag_pSEXP);
    Rcpp::traits::input_parameter< int >::type lag_q(lag_qSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type alg(algSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< bool >::type lag_single(lag_singleSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppContTE(mat, target, agent, lag_p, lag_q, k, alg, base, normalize, lag_single));
    return rcpp_result_gen;
END_RCPP
}
// RcppGenLatticeLag
Rcpp::NumericMatrix RcppGenLatticeLag(const Rcpp::NumericMatrix& mat, const Rcpp::List& nb, int lag);
RcppExport SEXP _infoxtr_RcppGenLatticeLag(SEXP matSEXP, SEXP nbSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenLatticeLag(mat, nb, lag));
    return rcpp_result_gen;
END_RCPP
}
// RcppGenGridLag
Rcpp::NumericMatrix RcppGenGridLag(const Rcpp::NumericMatrix& mat, int nrows, int lag);
RcppExport SEXP _infoxtr_RcppGenGridLag(SEXP matSEXP, SEXP nrowsSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenGridLag(mat, nrows, lag));
    return rcpp_result_gen;
END_RCPP
}
// RcppGenTSLag
Rcpp::NumericMatrix RcppGenTSLag(const Rcpp::NumericMatrix& mat, int lag);
RcppExport SEXP _infoxtr_RcppGenTSLag(SEXP matSEXP, SEXP lagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type lag(lagSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppGenTSLag(mat, lag));
    return rcpp_result_gen;
END_RCPP
}
// RcppNN4Mat
Rcpp::List RcppNN4Mat(const Rcpp::NumericMatrix& mat, int k, std::string method, bool include_self, bool byrow);
RcppExport SEXP _infoxtr_RcppNN4Mat(SEXP matSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP include_selfSEXP, SEXP byrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    Rcpp::traits::input_parameter< bool >::type byrow(byrowSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppNN4Mat(mat, k, method, include_self, byrow));
    return rcpp_result_gen;
END_RCPP
}
// RcppNN4MatSub
Rcpp::List RcppNN4MatSub(const Rcpp::NumericMatrix& mat, const Rcpp::IntegerVector& lib, const Rcpp::IntegerVector& pred, int k, std::string method, bool include_self, bool byrow);
RcppExport SEXP _infoxtr_RcppNN4MatSub(SEXP matSEXP, SEXP libSEXP, SEXP predSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP include_selfSEXP, SEXP byrowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type lib(libSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    Rcpp::traits::input_parameter< bool >::type byrow(byrowSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppNN4MatSub(mat, lib, pred, k, method, include_self, byrow));
    return rcpp_result_gen;
END_RCPP
}
// RcppNN4DistMat
Rcpp::List RcppNN4DistMat(const Rcpp::NumericMatrix& distmat, int k, bool include_self);
RcppExport SEXP _infoxtr_RcppNN4DistMat(SEXP distmatSEXP, SEXP kSEXP, SEXP include_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppNN4DistMat(distmat, k, include_self));
    return rcpp_result_gen;
END_RCPP
}
// RcppNN4DistMatSub
Rcpp::List RcppNN4DistMatSub(const Rcpp::NumericMatrix& distmat, const Rcpp::IntegerVector& lib, const Rcpp::IntegerVector& pred, int k, bool include_self);
RcppExport SEXP _infoxtr_RcppNN4DistMatSub(SEXP distmatSEXP, SEXP libSEXP, SEXP predSEXP, SEXP kSEXP, SEXP include_selfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type distmat(distmatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type lib(libSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type pred(predSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self(include_selfSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppNN4DistMatSub(distmat, lib, pred, k, include_self));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_infoxtr_RcppDisc", (DL_FUNC) &_infoxtr_RcppDisc, 10},
    {"_infoxtr_RcppDist4Vec", (DL_FUNC) &_infoxtr_RcppDist4Vec, 4},
    {"_infoxtr_RcppDist4Mat", (DL_FUNC) &_infoxtr_RcppDist4Mat, 4},
    {"_infoxtr_RcppDist4MatSub", (DL_FUNC) &_infoxtr_RcppDist4MatSub, 6},
    {"_infoxtr_RcppDiscEntropy", (DL_FUNC) &_infoxtr_RcppDiscEntropy, 3},
    {"_infoxtr_RcppContEntropy", (DL_FUNC) &_infoxtr_RcppContEntropy, 4},
    {"_infoxtr_RcppDiscJE", (DL_FUNC) &_infoxtr_RcppDiscJE, 4},
    {"_infoxtr_RcppContJE", (DL_FUNC) &_infoxtr_RcppContJE, 5},
    {"_infoxtr_RcppDiscCE", (DL_FUNC) &_infoxtr_RcppDiscCE, 5},
    {"_infoxtr_RcppContCE", (DL_FUNC) &_infoxtr_RcppContCE, 6},
    {"_infoxtr_RcppDiscMI", (DL_FUNC) &_infoxtr_RcppDiscMI, 6},
    {"_infoxtr_RcppContMI", (DL_FUNC) &_infoxtr_RcppContMI, 7},
    {"_infoxtr_RcppDiscCMI", (DL_FUNC) &_infoxtr_RcppDiscCMI, 7},
    {"_infoxtr_RcppContCMI", (DL_FUNC) &_infoxtr_RcppContCMI, 8},
    {"_infoxtr_RcppDiscTE", (DL_FUNC) &_infoxtr_RcppDiscTE, 9},
    {"_infoxtr_RcppContTE", (DL_FUNC) &_infoxtr_RcppContTE, 10},
    {"_infoxtr_RcppGenLatticeLag", (DL_FUNC) &_infoxtr_RcppGenLatticeLag, 3},
    {"_infoxtr_RcppGenGridLag", (DL_FUNC) &_infoxtr_RcppGenGridLag, 3},
    {"_infoxtr_RcppGenTSLag", (DL_FUNC) &_infoxtr_RcppGenTSLag, 2},
    {"_infoxtr_RcppNN4Mat", (DL_FUNC) &_infoxtr_RcppNN4Mat, 5},
    {"_infoxtr_RcppNN4MatSub", (DL_FUNC) &_infoxtr_RcppNN4MatSub, 7},
    {"_infoxtr_RcppNN4DistMat", (DL_FUNC) &_infoxtr_RcppNN4DistMat, 3},
    {"_infoxtr_RcppNN4DistMatSub", (DL_FUNC) &_infoxtr_RcppNN4DistMatSub, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_infoxtr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
