# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppGenLatticeLag <- function(mat, nb, lag = 1L) {
    .Call(`_infocaus_RcppGenLatticeLag`, mat, nb, lag)
}

